import {
  LucideBanknoteArrowDown,
  LucideBanknoteArrowUp,
  LucideChevronDown,
  LucideChevronRight,
  LucideCirclePlus,
  LucideCircleUserRound,
  LucideCloud,
  LucideDownload,
  LucideEllipsis,
  LucideFileCheck,
  LucideFileImage,
  LucideFileSpreadsheet,
  LucideFileText,
  LucideHouse,
  LucideLandmark,
  LucideLayoutDashboard,
  LucideListTree,
  LucideLogIn,
  LucideLogOut,
  LucideMenu,
  LucidePalette,
  LucideRefreshCcw,
  LucideSquareUser,
  LucideTriangleAlert,
  LucideUndo2,
  LucideUpload,
  LucideUserCog,
  LucideUserRound,
  LucideUserRoundKey,
  LucideUsers,
  LucideWalletMinimal,
  LucideX,
} from '@lucide/angular';

export const APP_ICONS = {
  LucideTriangleAlert,
  LucideCloud,
  LucideCircleUserRound,
  LucideX,
  LucideCirclePlus,
  LucideRefreshCcw,
  LucideHouse,
  LucideUserRound,
  LucideUserRoundKey,
  LucideLandmark,
  LucideLayoutDashboard,
  LucidePalette,
  LucideBanknoteArrowUp,
  LucideBanknoteArrowDown,
  LucideDownload,
  LucideEllipsis,
  LucideFileCheck,
  LucideFileImage,
  LucideFileSpreadsheet,
  LucideFileText,
  LucideLogOut,
  LucideLogIn,
  LucideWalletMinimal,
  LucideUsers,
  LucideListTree,
  LucideChevronDown,
  LucideChevronRight,
  LucideMenu,
  LucideSquareUser,
  LucideUpload,
  LucideUserCog,
  LucideUndo2,
} as const;

export type AppIconName = keyof typeof APP_ICONS;
